name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Install dependencies
      run: dotnet restore ./TestAutomationPOCSite/TestAutomationPOCSite.sln

    - name: Build the solution
      run: dotnet build ./TestAutomationPOCSite/TestAutomationPOCSite.sln --configuration Release


    - name: Install Chromium
      run: |
        sudo apt update
        sudo apt install -y chromium-browser

    - name: Set CHROME_BIN and CHROMEDRIVER
      run: |
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "CHROMEDRIVER=/usr/bin/chromedriver" >> $GITHUB_ENV

    - name: Run Selenium Tests
      run: dotnet test ./TestAutomationPOCSite/TestAutomationPOCSite.sln --configuration Release --logger "console;verbosity=normal"